// Code generated by SQLBoiler 4.9.2 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

var TableNames = struct {
	ChatTweetSubscriptions string
	Chats                  string
	Messages               string
	Senders                string
	TweetUsers             string
}{
	ChatTweetSubscriptions: "chat_tweet_subscriptions",
	Chats:                  "chats",
	Messages:               "messages",
	Senders:                "senders",
	TweetUsers:             "tweet_users",
}
