// Code generated by entc, DO NOT EDIT.

package tweetuser

const (
	// Label holds the string label denoting the tweetuser type in the database.
	Label = "tweet_user"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldUsername holds the string denoting the username field in the database.
	FieldUsername = "username"
	// Table holds the table name of the tweetuser in the database.
	Table = "tweet_users"
)

// Columns holds all SQL columns for tweetuser fields.
var Columns = []string{
	FieldID,
	FieldUsername,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}
