// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Chat is the predicate function for chat builders.
type Chat func(*sql.Selector)

// ChatTweetSubscription is the predicate function for chattweetsubscription builders.
type ChatTweetSubscription func(*sql.Selector)

// Message is the predicate function for message builders.
type Message func(*sql.Selector)

// Sender is the predicate function for sender builders.
type Sender func(*sql.Selector)

// TweetUser is the predicate function for tweetuser builders.
type TweetUser func(*sql.Selector)
