qutoes: 
  - '笑死'
  - '挺好'
  - '素'
  - 'ao'

repeater:
  rand:
    start: 20
    end: 50

mlcapi:
  lockto:
    - example user
    - another user
  token:
    staff: sometoken
    man: sometoken

avatar_sync: ""