// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/0w0mewo/mcrc_tgbot/persistent/ent/chat"
	"github.com/0w0mewo/mcrc_tgbot/persistent/ent/chattweetsubscription"
	"github.com/0w0mewo/mcrc_tgbot/persistent/ent/predicate"
	"github.com/0w0mewo/mcrc_tgbot/persistent/ent/tweetuser"
)

// ChatTweetSubscriptionQuery is the builder for querying ChatTweetSubscription entities.
type ChatTweetSubscriptionQuery struct {
	config
	limit      *int
	offset     *int
	unique     *bool
	order      []OrderFunc
	fields     []string
	predicates []predicate.ChatTweetSubscription
	// eager-loading edges.
	withSubscribedTweeter *TweetUserQuery
	withSubscribedChat    *ChatQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the ChatTweetSubscriptionQuery builder.
func (ctsq *ChatTweetSubscriptionQuery) Where(ps ...predicate.ChatTweetSubscription) *ChatTweetSubscriptionQuery {
	ctsq.predicates = append(ctsq.predicates, ps...)
	return ctsq
}

// Limit adds a limit step to the query.
func (ctsq *ChatTweetSubscriptionQuery) Limit(limit int) *ChatTweetSubscriptionQuery {
	ctsq.limit = &limit
	return ctsq
}

// Offset adds an offset step to the query.
func (ctsq *ChatTweetSubscriptionQuery) Offset(offset int) *ChatTweetSubscriptionQuery {
	ctsq.offset = &offset
	return ctsq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (ctsq *ChatTweetSubscriptionQuery) Unique(unique bool) *ChatTweetSubscriptionQuery {
	ctsq.unique = &unique
	return ctsq
}

// Order adds an order step to the query.
func (ctsq *ChatTweetSubscriptionQuery) Order(o ...OrderFunc) *ChatTweetSubscriptionQuery {
	ctsq.order = append(ctsq.order, o...)
	return ctsq
}

// QuerySubscribedTweeter chains the current query on the "subscribed_tweeter" edge.
func (ctsq *ChatTweetSubscriptionQuery) QuerySubscribedTweeter() *TweetUserQuery {
	query := &TweetUserQuery{config: ctsq.config}
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := ctsq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := ctsq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(chattweetsubscription.Table, chattweetsubscription.FieldID, selector),
			sqlgraph.To(tweetuser.Table, tweetuser.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, chattweetsubscription.SubscribedTweeterTable, chattweetsubscription.SubscribedTweeterColumn),
		)
		fromU = sqlgraph.SetNeighbors(ctsq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QuerySubscribedChat chains the current query on the "subscribed_chat" edge.
func (ctsq *ChatTweetSubscriptionQuery) QuerySubscribedChat() *ChatQuery {
	query := &ChatQuery{config: ctsq.config}
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := ctsq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := ctsq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(chattweetsubscription.Table, chattweetsubscription.FieldID, selector),
			sqlgraph.To(chat.Table, chat.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, chattweetsubscription.SubscribedChatTable, chattweetsubscription.SubscribedChatColumn),
		)
		fromU = sqlgraph.SetNeighbors(ctsq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first ChatTweetSubscription entity from the query.
// Returns a *NotFoundError when no ChatTweetSubscription was found.
func (ctsq *ChatTweetSubscriptionQuery) First(ctx context.Context) (*ChatTweetSubscription, error) {
	nodes, err := ctsq.Limit(1).All(ctx)
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{chattweetsubscription.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (ctsq *ChatTweetSubscriptionQuery) FirstX(ctx context.Context) *ChatTweetSubscription {
	node, err := ctsq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first ChatTweetSubscription ID from the query.
// Returns a *NotFoundError when no ChatTweetSubscription ID was found.
func (ctsq *ChatTweetSubscriptionQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = ctsq.Limit(1).IDs(ctx); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{chattweetsubscription.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (ctsq *ChatTweetSubscriptionQuery) FirstIDX(ctx context.Context) int {
	id, err := ctsq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single ChatTweetSubscription entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one ChatTweetSubscription entity is found.
// Returns a *NotFoundError when no ChatTweetSubscription entities are found.
func (ctsq *ChatTweetSubscriptionQuery) Only(ctx context.Context) (*ChatTweetSubscription, error) {
	nodes, err := ctsq.Limit(2).All(ctx)
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{chattweetsubscription.Label}
	default:
		return nil, &NotSingularError{chattweetsubscription.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (ctsq *ChatTweetSubscriptionQuery) OnlyX(ctx context.Context) *ChatTweetSubscription {
	node, err := ctsq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only ChatTweetSubscription ID in the query.
// Returns a *NotSingularError when more than one ChatTweetSubscription ID is found.
// Returns a *NotFoundError when no entities are found.
func (ctsq *ChatTweetSubscriptionQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = ctsq.Limit(2).IDs(ctx); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{chattweetsubscription.Label}
	default:
		err = &NotSingularError{chattweetsubscription.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (ctsq *ChatTweetSubscriptionQuery) OnlyIDX(ctx context.Context) int {
	id, err := ctsq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of ChatTweetSubscriptions.
func (ctsq *ChatTweetSubscriptionQuery) All(ctx context.Context) ([]*ChatTweetSubscription, error) {
	if err := ctsq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	return ctsq.sqlAll(ctx)
}

// AllX is like All, but panics if an error occurs.
func (ctsq *ChatTweetSubscriptionQuery) AllX(ctx context.Context) []*ChatTweetSubscription {
	nodes, err := ctsq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of ChatTweetSubscription IDs.
func (ctsq *ChatTweetSubscriptionQuery) IDs(ctx context.Context) ([]int, error) {
	var ids []int
	if err := ctsq.Select(chattweetsubscription.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (ctsq *ChatTweetSubscriptionQuery) IDsX(ctx context.Context) []int {
	ids, err := ctsq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (ctsq *ChatTweetSubscriptionQuery) Count(ctx context.Context) (int, error) {
	if err := ctsq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return ctsq.sqlCount(ctx)
}

// CountX is like Count, but panics if an error occurs.
func (ctsq *ChatTweetSubscriptionQuery) CountX(ctx context.Context) int {
	count, err := ctsq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (ctsq *ChatTweetSubscriptionQuery) Exist(ctx context.Context) (bool, error) {
	if err := ctsq.prepareQuery(ctx); err != nil {
		return false, err
	}
	return ctsq.sqlExist(ctx)
}

// ExistX is like Exist, but panics if an error occurs.
func (ctsq *ChatTweetSubscriptionQuery) ExistX(ctx context.Context) bool {
	exist, err := ctsq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the ChatTweetSubscriptionQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (ctsq *ChatTweetSubscriptionQuery) Clone() *ChatTweetSubscriptionQuery {
	if ctsq == nil {
		return nil
	}
	return &ChatTweetSubscriptionQuery{
		config:                ctsq.config,
		limit:                 ctsq.limit,
		offset:                ctsq.offset,
		order:                 append([]OrderFunc{}, ctsq.order...),
		predicates:            append([]predicate.ChatTweetSubscription{}, ctsq.predicates...),
		withSubscribedTweeter: ctsq.withSubscribedTweeter.Clone(),
		withSubscribedChat:    ctsq.withSubscribedChat.Clone(),
		// clone intermediate query.
		sql:    ctsq.sql.Clone(),
		path:   ctsq.path,
		unique: ctsq.unique,
	}
}

// WithSubscribedTweeter tells the query-builder to eager-load the nodes that are connected to
// the "subscribed_tweeter" edge. The optional arguments are used to configure the query builder of the edge.
func (ctsq *ChatTweetSubscriptionQuery) WithSubscribedTweeter(opts ...func(*TweetUserQuery)) *ChatTweetSubscriptionQuery {
	query := &TweetUserQuery{config: ctsq.config}
	for _, opt := range opts {
		opt(query)
	}
	ctsq.withSubscribedTweeter = query
	return ctsq
}

// WithSubscribedChat tells the query-builder to eager-load the nodes that are connected to
// the "subscribed_chat" edge. The optional arguments are used to configure the query builder of the edge.
func (ctsq *ChatTweetSubscriptionQuery) WithSubscribedChat(opts ...func(*ChatQuery)) *ChatTweetSubscriptionQuery {
	query := &ChatQuery{config: ctsq.config}
	for _, opt := range opts {
		opt(query)
	}
	ctsq.withSubscribedChat = query
	return ctsq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		ChatID int64 `json:"chat_id,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.ChatTweetSubscription.Query().
//		GroupBy(chattweetsubscription.FieldChatID).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
//
func (ctsq *ChatTweetSubscriptionQuery) GroupBy(field string, fields ...string) *ChatTweetSubscriptionGroupBy {
	group := &ChatTweetSubscriptionGroupBy{config: ctsq.config}
	group.fields = append([]string{field}, fields...)
	group.path = func(ctx context.Context) (prev *sql.Selector, err error) {
		if err := ctsq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		return ctsq.sqlQuery(ctx), nil
	}
	return group
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		ChatID int64 `json:"chat_id,omitempty"`
//	}
//
//	client.ChatTweetSubscription.Query().
//		Select(chattweetsubscription.FieldChatID).
//		Scan(ctx, &v)
//
func (ctsq *ChatTweetSubscriptionQuery) Select(fields ...string) *ChatTweetSubscriptionSelect {
	ctsq.fields = append(ctsq.fields, fields...)
	return &ChatTweetSubscriptionSelect{ChatTweetSubscriptionQuery: ctsq}
}

func (ctsq *ChatTweetSubscriptionQuery) prepareQuery(ctx context.Context) error {
	for _, f := range ctsq.fields {
		if !chattweetsubscription.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if ctsq.path != nil {
		prev, err := ctsq.path(ctx)
		if err != nil {
			return err
		}
		ctsq.sql = prev
	}
	return nil
}

func (ctsq *ChatTweetSubscriptionQuery) sqlAll(ctx context.Context) ([]*ChatTweetSubscription, error) {
	var (
		nodes       = []*ChatTweetSubscription{}
		_spec       = ctsq.querySpec()
		loadedTypes = [2]bool{
			ctsq.withSubscribedTweeter != nil,
			ctsq.withSubscribedChat != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]interface{}, error) {
		node := &ChatTweetSubscription{config: ctsq.config}
		nodes = append(nodes, node)
		return node.scanValues(columns)
	}
	_spec.Assign = func(columns []string, values []interface{}) error {
		if len(nodes) == 0 {
			return fmt.Errorf("ent: Assign called without calling ScanValues")
		}
		node := nodes[len(nodes)-1]
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	if err := sqlgraph.QueryNodes(ctx, ctsq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}

	if query := ctsq.withSubscribedTweeter; query != nil {
		ids := make([]string, 0, len(nodes))
		nodeids := make(map[string][]*ChatTweetSubscription)
		for i := range nodes {
			fk := nodes[i].TweeterID
			if _, ok := nodeids[fk]; !ok {
				ids = append(ids, fk)
			}
			nodeids[fk] = append(nodeids[fk], nodes[i])
		}
		query.Where(tweetuser.IDIn(ids...))
		neighbors, err := query.All(ctx)
		if err != nil {
			return nil, err
		}
		for _, n := range neighbors {
			nodes, ok := nodeids[n.ID]
			if !ok {
				return nil, fmt.Errorf(`unexpected foreign-key "tweeter_id" returned %v`, n.ID)
			}
			for i := range nodes {
				nodes[i].Edges.SubscribedTweeter = n
			}
		}
	}

	if query := ctsq.withSubscribedChat; query != nil {
		ids := make([]int64, 0, len(nodes))
		nodeids := make(map[int64][]*ChatTweetSubscription)
		for i := range nodes {
			fk := nodes[i].ChatID
			if _, ok := nodeids[fk]; !ok {
				ids = append(ids, fk)
			}
			nodeids[fk] = append(nodeids[fk], nodes[i])
		}
		query.Where(chat.IDIn(ids...))
		neighbors, err := query.All(ctx)
		if err != nil {
			return nil, err
		}
		for _, n := range neighbors {
			nodes, ok := nodeids[n.ID]
			if !ok {
				return nil, fmt.Errorf(`unexpected foreign-key "chat_id" returned %v`, n.ID)
			}
			for i := range nodes {
				nodes[i].Edges.SubscribedChat = n
			}
		}
	}

	return nodes, nil
}

func (ctsq *ChatTweetSubscriptionQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := ctsq.querySpec()
	_spec.Node.Columns = ctsq.fields
	if len(ctsq.fields) > 0 {
		_spec.Unique = ctsq.unique != nil && *ctsq.unique
	}
	return sqlgraph.CountNodes(ctx, ctsq.driver, _spec)
}

func (ctsq *ChatTweetSubscriptionQuery) sqlExist(ctx context.Context) (bool, error) {
	n, err := ctsq.sqlCount(ctx)
	if err != nil {
		return false, fmt.Errorf("ent: check existence: %w", err)
	}
	return n > 0, nil
}

func (ctsq *ChatTweetSubscriptionQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := &sqlgraph.QuerySpec{
		Node: &sqlgraph.NodeSpec{
			Table:   chattweetsubscription.Table,
			Columns: chattweetsubscription.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: chattweetsubscription.FieldID,
			},
		},
		From:   ctsq.sql,
		Unique: true,
	}
	if unique := ctsq.unique; unique != nil {
		_spec.Unique = *unique
	}
	if fields := ctsq.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, chattweetsubscription.FieldID)
		for i := range fields {
			if fields[i] != chattweetsubscription.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := ctsq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := ctsq.limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := ctsq.offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := ctsq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (ctsq *ChatTweetSubscriptionQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(ctsq.driver.Dialect())
	t1 := builder.Table(chattweetsubscription.Table)
	columns := ctsq.fields
	if len(columns) == 0 {
		columns = chattweetsubscription.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if ctsq.sql != nil {
		selector = ctsq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if ctsq.unique != nil && *ctsq.unique {
		selector.Distinct()
	}
	for _, p := range ctsq.predicates {
		p(selector)
	}
	for _, p := range ctsq.order {
		p(selector)
	}
	if offset := ctsq.offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := ctsq.limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// ChatTweetSubscriptionGroupBy is the group-by builder for ChatTweetSubscription entities.
type ChatTweetSubscriptionGroupBy struct {
	config
	fields []string
	fns    []AggregateFunc
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Aggregate adds the given aggregation functions to the group-by query.
func (ctsgb *ChatTweetSubscriptionGroupBy) Aggregate(fns ...AggregateFunc) *ChatTweetSubscriptionGroupBy {
	ctsgb.fns = append(ctsgb.fns, fns...)
	return ctsgb
}

// Scan applies the group-by query and scans the result into the given value.
func (ctsgb *ChatTweetSubscriptionGroupBy) Scan(ctx context.Context, v interface{}) error {
	query, err := ctsgb.path(ctx)
	if err != nil {
		return err
	}
	ctsgb.sql = query
	return ctsgb.sqlScan(ctx, v)
}

// ScanX is like Scan, but panics if an error occurs.
func (ctsgb *ChatTweetSubscriptionGroupBy) ScanX(ctx context.Context, v interface{}) {
	if err := ctsgb.Scan(ctx, v); err != nil {
		panic(err)
	}
}

// Strings returns list of strings from group-by.
// It is only allowed when executing a group-by query with one field.
func (ctsgb *ChatTweetSubscriptionGroupBy) Strings(ctx context.Context) ([]string, error) {
	if len(ctsgb.fields) > 1 {
		return nil, errors.New("ent: ChatTweetSubscriptionGroupBy.Strings is not achievable when grouping more than 1 field")
	}
	var v []string
	if err := ctsgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// StringsX is like Strings, but panics if an error occurs.
func (ctsgb *ChatTweetSubscriptionGroupBy) StringsX(ctx context.Context) []string {
	v, err := ctsgb.Strings(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// String returns a single string from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (ctsgb *ChatTweetSubscriptionGroupBy) String(ctx context.Context) (_ string, err error) {
	var v []string
	if v, err = ctsgb.Strings(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{chattweetsubscription.Label}
	default:
		err = fmt.Errorf("ent: ChatTweetSubscriptionGroupBy.Strings returned %d results when one was expected", len(v))
	}
	return
}

// StringX is like String, but panics if an error occurs.
func (ctsgb *ChatTweetSubscriptionGroupBy) StringX(ctx context.Context) string {
	v, err := ctsgb.String(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Ints returns list of ints from group-by.
// It is only allowed when executing a group-by query with one field.
func (ctsgb *ChatTweetSubscriptionGroupBy) Ints(ctx context.Context) ([]int, error) {
	if len(ctsgb.fields) > 1 {
		return nil, errors.New("ent: ChatTweetSubscriptionGroupBy.Ints is not achievable when grouping more than 1 field")
	}
	var v []int
	if err := ctsgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// IntsX is like Ints, but panics if an error occurs.
func (ctsgb *ChatTweetSubscriptionGroupBy) IntsX(ctx context.Context) []int {
	v, err := ctsgb.Ints(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Int returns a single int from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (ctsgb *ChatTweetSubscriptionGroupBy) Int(ctx context.Context) (_ int, err error) {
	var v []int
	if v, err = ctsgb.Ints(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{chattweetsubscription.Label}
	default:
		err = fmt.Errorf("ent: ChatTweetSubscriptionGroupBy.Ints returned %d results when one was expected", len(v))
	}
	return
}

// IntX is like Int, but panics if an error occurs.
func (ctsgb *ChatTweetSubscriptionGroupBy) IntX(ctx context.Context) int {
	v, err := ctsgb.Int(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64s returns list of float64s from group-by.
// It is only allowed when executing a group-by query with one field.
func (ctsgb *ChatTweetSubscriptionGroupBy) Float64s(ctx context.Context) ([]float64, error) {
	if len(ctsgb.fields) > 1 {
		return nil, errors.New("ent: ChatTweetSubscriptionGroupBy.Float64s is not achievable when grouping more than 1 field")
	}
	var v []float64
	if err := ctsgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// Float64sX is like Float64s, but panics if an error occurs.
func (ctsgb *ChatTweetSubscriptionGroupBy) Float64sX(ctx context.Context) []float64 {
	v, err := ctsgb.Float64s(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64 returns a single float64 from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (ctsgb *ChatTweetSubscriptionGroupBy) Float64(ctx context.Context) (_ float64, err error) {
	var v []float64
	if v, err = ctsgb.Float64s(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{chattweetsubscription.Label}
	default:
		err = fmt.Errorf("ent: ChatTweetSubscriptionGroupBy.Float64s returned %d results when one was expected", len(v))
	}
	return
}

// Float64X is like Float64, but panics if an error occurs.
func (ctsgb *ChatTweetSubscriptionGroupBy) Float64X(ctx context.Context) float64 {
	v, err := ctsgb.Float64(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bools returns list of bools from group-by.
// It is only allowed when executing a group-by query with one field.
func (ctsgb *ChatTweetSubscriptionGroupBy) Bools(ctx context.Context) ([]bool, error) {
	if len(ctsgb.fields) > 1 {
		return nil, errors.New("ent: ChatTweetSubscriptionGroupBy.Bools is not achievable when grouping more than 1 field")
	}
	var v []bool
	if err := ctsgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// BoolsX is like Bools, but panics if an error occurs.
func (ctsgb *ChatTweetSubscriptionGroupBy) BoolsX(ctx context.Context) []bool {
	v, err := ctsgb.Bools(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bool returns a single bool from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (ctsgb *ChatTweetSubscriptionGroupBy) Bool(ctx context.Context) (_ bool, err error) {
	var v []bool
	if v, err = ctsgb.Bools(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{chattweetsubscription.Label}
	default:
		err = fmt.Errorf("ent: ChatTweetSubscriptionGroupBy.Bools returned %d results when one was expected", len(v))
	}
	return
}

// BoolX is like Bool, but panics if an error occurs.
func (ctsgb *ChatTweetSubscriptionGroupBy) BoolX(ctx context.Context) bool {
	v, err := ctsgb.Bool(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (ctsgb *ChatTweetSubscriptionGroupBy) sqlScan(ctx context.Context, v interface{}) error {
	for _, f := range ctsgb.fields {
		if !chattweetsubscription.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("invalid field %q for group-by", f)}
		}
	}
	selector := ctsgb.sqlQuery()
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := ctsgb.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

func (ctsgb *ChatTweetSubscriptionGroupBy) sqlQuery() *sql.Selector {
	selector := ctsgb.sql.Select()
	aggregation := make([]string, 0, len(ctsgb.fns))
	for _, fn := range ctsgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	// If no columns were selected in a custom aggregation function, the default
	// selection is the fields used for "group-by", and the aggregation functions.
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(ctsgb.fields)+len(ctsgb.fns))
		for _, f := range ctsgb.fields {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	return selector.GroupBy(selector.Columns(ctsgb.fields...)...)
}

// ChatTweetSubscriptionSelect is the builder for selecting fields of ChatTweetSubscription entities.
type ChatTweetSubscriptionSelect struct {
	*ChatTweetSubscriptionQuery
	// intermediate query (i.e. traversal path).
	sql *sql.Selector
}

// Scan applies the selector query and scans the result into the given value.
func (ctss *ChatTweetSubscriptionSelect) Scan(ctx context.Context, v interface{}) error {
	if err := ctss.prepareQuery(ctx); err != nil {
		return err
	}
	ctss.sql = ctss.ChatTweetSubscriptionQuery.sqlQuery(ctx)
	return ctss.sqlScan(ctx, v)
}

// ScanX is like Scan, but panics if an error occurs.
func (ctss *ChatTweetSubscriptionSelect) ScanX(ctx context.Context, v interface{}) {
	if err := ctss.Scan(ctx, v); err != nil {
		panic(err)
	}
}

// Strings returns list of strings from a selector. It is only allowed when selecting one field.
func (ctss *ChatTweetSubscriptionSelect) Strings(ctx context.Context) ([]string, error) {
	if len(ctss.fields) > 1 {
		return nil, errors.New("ent: ChatTweetSubscriptionSelect.Strings is not achievable when selecting more than 1 field")
	}
	var v []string
	if err := ctss.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// StringsX is like Strings, but panics if an error occurs.
func (ctss *ChatTweetSubscriptionSelect) StringsX(ctx context.Context) []string {
	v, err := ctss.Strings(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// String returns a single string from a selector. It is only allowed when selecting one field.
func (ctss *ChatTweetSubscriptionSelect) String(ctx context.Context) (_ string, err error) {
	var v []string
	if v, err = ctss.Strings(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{chattweetsubscription.Label}
	default:
		err = fmt.Errorf("ent: ChatTweetSubscriptionSelect.Strings returned %d results when one was expected", len(v))
	}
	return
}

// StringX is like String, but panics if an error occurs.
func (ctss *ChatTweetSubscriptionSelect) StringX(ctx context.Context) string {
	v, err := ctss.String(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Ints returns list of ints from a selector. It is only allowed when selecting one field.
func (ctss *ChatTweetSubscriptionSelect) Ints(ctx context.Context) ([]int, error) {
	if len(ctss.fields) > 1 {
		return nil, errors.New("ent: ChatTweetSubscriptionSelect.Ints is not achievable when selecting more than 1 field")
	}
	var v []int
	if err := ctss.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// IntsX is like Ints, but panics if an error occurs.
func (ctss *ChatTweetSubscriptionSelect) IntsX(ctx context.Context) []int {
	v, err := ctss.Ints(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Int returns a single int from a selector. It is only allowed when selecting one field.
func (ctss *ChatTweetSubscriptionSelect) Int(ctx context.Context) (_ int, err error) {
	var v []int
	if v, err = ctss.Ints(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{chattweetsubscription.Label}
	default:
		err = fmt.Errorf("ent: ChatTweetSubscriptionSelect.Ints returned %d results when one was expected", len(v))
	}
	return
}

// IntX is like Int, but panics if an error occurs.
func (ctss *ChatTweetSubscriptionSelect) IntX(ctx context.Context) int {
	v, err := ctss.Int(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64s returns list of float64s from a selector. It is only allowed when selecting one field.
func (ctss *ChatTweetSubscriptionSelect) Float64s(ctx context.Context) ([]float64, error) {
	if len(ctss.fields) > 1 {
		return nil, errors.New("ent: ChatTweetSubscriptionSelect.Float64s is not achievable when selecting more than 1 field")
	}
	var v []float64
	if err := ctss.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// Float64sX is like Float64s, but panics if an error occurs.
func (ctss *ChatTweetSubscriptionSelect) Float64sX(ctx context.Context) []float64 {
	v, err := ctss.Float64s(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64 returns a single float64 from a selector. It is only allowed when selecting one field.
func (ctss *ChatTweetSubscriptionSelect) Float64(ctx context.Context) (_ float64, err error) {
	var v []float64
	if v, err = ctss.Float64s(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{chattweetsubscription.Label}
	default:
		err = fmt.Errorf("ent: ChatTweetSubscriptionSelect.Float64s returned %d results when one was expected", len(v))
	}
	return
}

// Float64X is like Float64, but panics if an error occurs.
func (ctss *ChatTweetSubscriptionSelect) Float64X(ctx context.Context) float64 {
	v, err := ctss.Float64(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bools returns list of bools from a selector. It is only allowed when selecting one field.
func (ctss *ChatTweetSubscriptionSelect) Bools(ctx context.Context) ([]bool, error) {
	if len(ctss.fields) > 1 {
		return nil, errors.New("ent: ChatTweetSubscriptionSelect.Bools is not achievable when selecting more than 1 field")
	}
	var v []bool
	if err := ctss.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// BoolsX is like Bools, but panics if an error occurs.
func (ctss *ChatTweetSubscriptionSelect) BoolsX(ctx context.Context) []bool {
	v, err := ctss.Bools(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bool returns a single bool from a selector. It is only allowed when selecting one field.
func (ctss *ChatTweetSubscriptionSelect) Bool(ctx context.Context) (_ bool, err error) {
	var v []bool
	if v, err = ctss.Bools(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{chattweetsubscription.Label}
	default:
		err = fmt.Errorf("ent: ChatTweetSubscriptionSelect.Bools returned %d results when one was expected", len(v))
	}
	return
}

// BoolX is like Bool, but panics if an error occurs.
func (ctss *ChatTweetSubscriptionSelect) BoolX(ctx context.Context) bool {
	v, err := ctss.Bool(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (ctss *ChatTweetSubscriptionSelect) sqlScan(ctx context.Context, v interface{}) error {
	rows := &sql.Rows{}
	query, args := ctss.sql.Query()
	if err := ctss.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
