// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/0w0mewo/mcrc_tgbot/persistent/ent/chattweetsubscription"
	"github.com/0w0mewo/mcrc_tgbot/persistent/ent/predicate"
)

// ChatTweetSubscriptionDelete is the builder for deleting a ChatTweetSubscription entity.
type ChatTweetSubscriptionDelete struct {
	config
	hooks    []Hook
	mutation *ChatTweetSubscriptionMutation
}

// Where appends a list predicates to the ChatTweetSubscriptionDelete builder.
func (ctsd *ChatTweetSubscriptionDelete) Where(ps ...predicate.ChatTweetSubscription) *ChatTweetSubscriptionDelete {
	ctsd.mutation.Where(ps...)
	return ctsd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (ctsd *ChatTweetSubscriptionDelete) Exec(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(ctsd.hooks) == 0 {
		affected, err = ctsd.sqlExec(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*ChatTweetSubscriptionMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			ctsd.mutation = mutation
			affected, err = ctsd.sqlExec(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(ctsd.hooks) - 1; i >= 0; i-- {
			if ctsd.hooks[i] == nil {
				return 0, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = ctsd.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, ctsd.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// ExecX is like Exec, but panics if an error occurs.
func (ctsd *ChatTweetSubscriptionDelete) ExecX(ctx context.Context) int {
	n, err := ctsd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (ctsd *ChatTweetSubscriptionDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := &sqlgraph.DeleteSpec{
		Node: &sqlgraph.NodeSpec{
			Table: chattweetsubscription.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: chattweetsubscription.FieldID,
			},
		},
	}
	if ps := ctsd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return sqlgraph.DeleteNodes(ctx, ctsd.driver, _spec)
}

// ChatTweetSubscriptionDeleteOne is the builder for deleting a single ChatTweetSubscription entity.
type ChatTweetSubscriptionDeleteOne struct {
	ctsd *ChatTweetSubscriptionDelete
}

// Exec executes the deletion query.
func (ctsdo *ChatTweetSubscriptionDeleteOne) Exec(ctx context.Context) error {
	n, err := ctsdo.ctsd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{chattweetsubscription.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (ctsdo *ChatTweetSubscriptionDeleteOne) ExecX(ctx context.Context) {
	ctsdo.ctsd.ExecX(ctx)
}
