// Code generated by entc, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"

	"entgo.io/ent/dialect/sql"
	"github.com/0w0mewo/mcrc_tgbot/persistent/ent/tweetuser"
)

// TweetUser is the model entity for the TweetUser schema.
type TweetUser struct {
	config `json:"-"`
	// ID of the ent.
	ID string `json:"id,omitempty"`
	// Username holds the value of the "username" field.
	Username string `json:"username,omitempty"`
}

// scanValues returns the types for scanning values from sql.Rows.
func (*TweetUser) scanValues(columns []string) ([]interface{}, error) {
	values := make([]interface{}, len(columns))
	for i := range columns {
		switch columns[i] {
		case tweetuser.FieldID, tweetuser.FieldUsername:
			values[i] = new(sql.NullString)
		default:
			return nil, fmt.Errorf("unexpected column %q for type TweetUser", columns[i])
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the TweetUser fields.
func (tu *TweetUser) assignValues(columns []string, values []interface{}) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case tweetuser.FieldID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value.Valid {
				tu.ID = value.String
			}
		case tweetuser.FieldUsername:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field username", values[i])
			} else if value.Valid {
				tu.Username = value.String
			}
		}
	}
	return nil
}

// Update returns a builder for updating this TweetUser.
// Note that you need to call TweetUser.Unwrap() before calling this method if this TweetUser
// was returned from a transaction, and the transaction was committed or rolled back.
func (tu *TweetUser) Update() *TweetUserUpdateOne {
	return (&TweetUserClient{config: tu.config}).UpdateOne(tu)
}

// Unwrap unwraps the TweetUser entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (tu *TweetUser) Unwrap() *TweetUser {
	tx, ok := tu.config.driver.(*txDriver)
	if !ok {
		panic("ent: TweetUser is not a transactional entity")
	}
	tu.config.driver = tx.drv
	return tu
}

// String implements the fmt.Stringer.
func (tu *TweetUser) String() string {
	var builder strings.Builder
	builder.WriteString("TweetUser(")
	builder.WriteString(fmt.Sprintf("id=%v", tu.ID))
	builder.WriteString(", username=")
	builder.WriteString(tu.Username)
	builder.WriteByte(')')
	return builder.String()
}

// TweetUsers is a parsable slice of TweetUser.
type TweetUsers []*TweetUser

func (tu TweetUsers) config(cfg config) {
	for _i := range tu {
		tu[_i].config = cfg
	}
}
