// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/0w0mewo/mcrc_tgbot/persistent/ent/predicate"
	"github.com/0w0mewo/mcrc_tgbot/persistent/ent/tweetuser"
)

// TweetUserDelete is the builder for deleting a TweetUser entity.
type TweetUserDelete struct {
	config
	hooks    []Hook
	mutation *TweetUserMutation
}

// Where appends a list predicates to the TweetUserDelete builder.
func (tud *TweetUserDelete) Where(ps ...predicate.TweetUser) *TweetUserDelete {
	tud.mutation.Where(ps...)
	return tud
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (tud *TweetUserDelete) Exec(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(tud.hooks) == 0 {
		affected, err = tud.sqlExec(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*TweetUserMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			tud.mutation = mutation
			affected, err = tud.sqlExec(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(tud.hooks) - 1; i >= 0; i-- {
			if tud.hooks[i] == nil {
				return 0, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = tud.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, tud.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// ExecX is like Exec, but panics if an error occurs.
func (tud *TweetUserDelete) ExecX(ctx context.Context) int {
	n, err := tud.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (tud *TweetUserDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := &sqlgraph.DeleteSpec{
		Node: &sqlgraph.NodeSpec{
			Table: tweetuser.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeString,
				Column: tweetuser.FieldID,
			},
		},
	}
	if ps := tud.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return sqlgraph.DeleteNodes(ctx, tud.driver, _spec)
}

// TweetUserDeleteOne is the builder for deleting a single TweetUser entity.
type TweetUserDeleteOne struct {
	tud *TweetUserDelete
}

// Exec executes the deletion query.
func (tudo *TweetUserDeleteOne) Exec(ctx context.Context) error {
	n, err := tudo.tud.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{tweetuser.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (tudo *TweetUserDeleteOne) ExecX(ctx context.Context) {
	tudo.tud.ExecX(ctx)
}
