// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/0w0mewo/mcrc_tgbot/persistent/ent/predicate"
	"github.com/0w0mewo/mcrc_tgbot/persistent/ent/tweetuser"
)

// TweetUserQuery is the builder for querying TweetUser entities.
type TweetUserQuery struct {
	config
	limit      *int
	offset     *int
	unique     *bool
	order      []OrderFunc
	fields     []string
	predicates []predicate.TweetUser
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the TweetUserQuery builder.
func (tuq *TweetUserQuery) Where(ps ...predicate.TweetUser) *TweetUserQuery {
	tuq.predicates = append(tuq.predicates, ps...)
	return tuq
}

// Limit adds a limit step to the query.
func (tuq *TweetUserQuery) Limit(limit int) *TweetUserQuery {
	tuq.limit = &limit
	return tuq
}

// Offset adds an offset step to the query.
func (tuq *TweetUserQuery) Offset(offset int) *TweetUserQuery {
	tuq.offset = &offset
	return tuq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (tuq *TweetUserQuery) Unique(unique bool) *TweetUserQuery {
	tuq.unique = &unique
	return tuq
}

// Order adds an order step to the query.
func (tuq *TweetUserQuery) Order(o ...OrderFunc) *TweetUserQuery {
	tuq.order = append(tuq.order, o...)
	return tuq
}

// First returns the first TweetUser entity from the query.
// Returns a *NotFoundError when no TweetUser was found.
func (tuq *TweetUserQuery) First(ctx context.Context) (*TweetUser, error) {
	nodes, err := tuq.Limit(1).All(ctx)
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{tweetuser.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (tuq *TweetUserQuery) FirstX(ctx context.Context) *TweetUser {
	node, err := tuq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first TweetUser ID from the query.
// Returns a *NotFoundError when no TweetUser ID was found.
func (tuq *TweetUserQuery) FirstID(ctx context.Context) (id string, err error) {
	var ids []string
	if ids, err = tuq.Limit(1).IDs(ctx); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{tweetuser.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (tuq *TweetUserQuery) FirstIDX(ctx context.Context) string {
	id, err := tuq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single TweetUser entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one TweetUser entity is found.
// Returns a *NotFoundError when no TweetUser entities are found.
func (tuq *TweetUserQuery) Only(ctx context.Context) (*TweetUser, error) {
	nodes, err := tuq.Limit(2).All(ctx)
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{tweetuser.Label}
	default:
		return nil, &NotSingularError{tweetuser.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (tuq *TweetUserQuery) OnlyX(ctx context.Context) *TweetUser {
	node, err := tuq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only TweetUser ID in the query.
// Returns a *NotSingularError when more than one TweetUser ID is found.
// Returns a *NotFoundError when no entities are found.
func (tuq *TweetUserQuery) OnlyID(ctx context.Context) (id string, err error) {
	var ids []string
	if ids, err = tuq.Limit(2).IDs(ctx); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{tweetuser.Label}
	default:
		err = &NotSingularError{tweetuser.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (tuq *TweetUserQuery) OnlyIDX(ctx context.Context) string {
	id, err := tuq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of TweetUsers.
func (tuq *TweetUserQuery) All(ctx context.Context) ([]*TweetUser, error) {
	if err := tuq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	return tuq.sqlAll(ctx)
}

// AllX is like All, but panics if an error occurs.
func (tuq *TweetUserQuery) AllX(ctx context.Context) []*TweetUser {
	nodes, err := tuq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of TweetUser IDs.
func (tuq *TweetUserQuery) IDs(ctx context.Context) ([]string, error) {
	var ids []string
	if err := tuq.Select(tweetuser.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (tuq *TweetUserQuery) IDsX(ctx context.Context) []string {
	ids, err := tuq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (tuq *TweetUserQuery) Count(ctx context.Context) (int, error) {
	if err := tuq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return tuq.sqlCount(ctx)
}

// CountX is like Count, but panics if an error occurs.
func (tuq *TweetUserQuery) CountX(ctx context.Context) int {
	count, err := tuq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (tuq *TweetUserQuery) Exist(ctx context.Context) (bool, error) {
	if err := tuq.prepareQuery(ctx); err != nil {
		return false, err
	}
	return tuq.sqlExist(ctx)
}

// ExistX is like Exist, but panics if an error occurs.
func (tuq *TweetUserQuery) ExistX(ctx context.Context) bool {
	exist, err := tuq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the TweetUserQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (tuq *TweetUserQuery) Clone() *TweetUserQuery {
	if tuq == nil {
		return nil
	}
	return &TweetUserQuery{
		config:     tuq.config,
		limit:      tuq.limit,
		offset:     tuq.offset,
		order:      append([]OrderFunc{}, tuq.order...),
		predicates: append([]predicate.TweetUser{}, tuq.predicates...),
		// clone intermediate query.
		sql:    tuq.sql.Clone(),
		path:   tuq.path,
		unique: tuq.unique,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Username string `json:"username,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.TweetUser.Query().
//		GroupBy(tweetuser.FieldUsername).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
//
func (tuq *TweetUserQuery) GroupBy(field string, fields ...string) *TweetUserGroupBy {
	group := &TweetUserGroupBy{config: tuq.config}
	group.fields = append([]string{field}, fields...)
	group.path = func(ctx context.Context) (prev *sql.Selector, err error) {
		if err := tuq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		return tuq.sqlQuery(ctx), nil
	}
	return group
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Username string `json:"username,omitempty"`
//	}
//
//	client.TweetUser.Query().
//		Select(tweetuser.FieldUsername).
//		Scan(ctx, &v)
//
func (tuq *TweetUserQuery) Select(fields ...string) *TweetUserSelect {
	tuq.fields = append(tuq.fields, fields...)
	return &TweetUserSelect{TweetUserQuery: tuq}
}

func (tuq *TweetUserQuery) prepareQuery(ctx context.Context) error {
	for _, f := range tuq.fields {
		if !tweetuser.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if tuq.path != nil {
		prev, err := tuq.path(ctx)
		if err != nil {
			return err
		}
		tuq.sql = prev
	}
	return nil
}

func (tuq *TweetUserQuery) sqlAll(ctx context.Context) ([]*TweetUser, error) {
	var (
		nodes = []*TweetUser{}
		_spec = tuq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]interface{}, error) {
		node := &TweetUser{config: tuq.config}
		nodes = append(nodes, node)
		return node.scanValues(columns)
	}
	_spec.Assign = func(columns []string, values []interface{}) error {
		if len(nodes) == 0 {
			return fmt.Errorf("ent: Assign called without calling ScanValues")
		}
		node := nodes[len(nodes)-1]
		return node.assignValues(columns, values)
	}
	if err := sqlgraph.QueryNodes(ctx, tuq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (tuq *TweetUserQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := tuq.querySpec()
	_spec.Node.Columns = tuq.fields
	if len(tuq.fields) > 0 {
		_spec.Unique = tuq.unique != nil && *tuq.unique
	}
	return sqlgraph.CountNodes(ctx, tuq.driver, _spec)
}

func (tuq *TweetUserQuery) sqlExist(ctx context.Context) (bool, error) {
	n, err := tuq.sqlCount(ctx)
	if err != nil {
		return false, fmt.Errorf("ent: check existence: %w", err)
	}
	return n > 0, nil
}

func (tuq *TweetUserQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := &sqlgraph.QuerySpec{
		Node: &sqlgraph.NodeSpec{
			Table:   tweetuser.Table,
			Columns: tweetuser.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeString,
				Column: tweetuser.FieldID,
			},
		},
		From:   tuq.sql,
		Unique: true,
	}
	if unique := tuq.unique; unique != nil {
		_spec.Unique = *unique
	}
	if fields := tuq.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, tweetuser.FieldID)
		for i := range fields {
			if fields[i] != tweetuser.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := tuq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := tuq.limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := tuq.offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := tuq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (tuq *TweetUserQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(tuq.driver.Dialect())
	t1 := builder.Table(tweetuser.Table)
	columns := tuq.fields
	if len(columns) == 0 {
		columns = tweetuser.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if tuq.sql != nil {
		selector = tuq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if tuq.unique != nil && *tuq.unique {
		selector.Distinct()
	}
	for _, p := range tuq.predicates {
		p(selector)
	}
	for _, p := range tuq.order {
		p(selector)
	}
	if offset := tuq.offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := tuq.limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// TweetUserGroupBy is the group-by builder for TweetUser entities.
type TweetUserGroupBy struct {
	config
	fields []string
	fns    []AggregateFunc
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Aggregate adds the given aggregation functions to the group-by query.
func (tugb *TweetUserGroupBy) Aggregate(fns ...AggregateFunc) *TweetUserGroupBy {
	tugb.fns = append(tugb.fns, fns...)
	return tugb
}

// Scan applies the group-by query and scans the result into the given value.
func (tugb *TweetUserGroupBy) Scan(ctx context.Context, v interface{}) error {
	query, err := tugb.path(ctx)
	if err != nil {
		return err
	}
	tugb.sql = query
	return tugb.sqlScan(ctx, v)
}

// ScanX is like Scan, but panics if an error occurs.
func (tugb *TweetUserGroupBy) ScanX(ctx context.Context, v interface{}) {
	if err := tugb.Scan(ctx, v); err != nil {
		panic(err)
	}
}

// Strings returns list of strings from group-by.
// It is only allowed when executing a group-by query with one field.
func (tugb *TweetUserGroupBy) Strings(ctx context.Context) ([]string, error) {
	if len(tugb.fields) > 1 {
		return nil, errors.New("ent: TweetUserGroupBy.Strings is not achievable when grouping more than 1 field")
	}
	var v []string
	if err := tugb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// StringsX is like Strings, but panics if an error occurs.
func (tugb *TweetUserGroupBy) StringsX(ctx context.Context) []string {
	v, err := tugb.Strings(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// String returns a single string from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (tugb *TweetUserGroupBy) String(ctx context.Context) (_ string, err error) {
	var v []string
	if v, err = tugb.Strings(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{tweetuser.Label}
	default:
		err = fmt.Errorf("ent: TweetUserGroupBy.Strings returned %d results when one was expected", len(v))
	}
	return
}

// StringX is like String, but panics if an error occurs.
func (tugb *TweetUserGroupBy) StringX(ctx context.Context) string {
	v, err := tugb.String(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Ints returns list of ints from group-by.
// It is only allowed when executing a group-by query with one field.
func (tugb *TweetUserGroupBy) Ints(ctx context.Context) ([]int, error) {
	if len(tugb.fields) > 1 {
		return nil, errors.New("ent: TweetUserGroupBy.Ints is not achievable when grouping more than 1 field")
	}
	var v []int
	if err := tugb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// IntsX is like Ints, but panics if an error occurs.
func (tugb *TweetUserGroupBy) IntsX(ctx context.Context) []int {
	v, err := tugb.Ints(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Int returns a single int from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (tugb *TweetUserGroupBy) Int(ctx context.Context) (_ int, err error) {
	var v []int
	if v, err = tugb.Ints(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{tweetuser.Label}
	default:
		err = fmt.Errorf("ent: TweetUserGroupBy.Ints returned %d results when one was expected", len(v))
	}
	return
}

// IntX is like Int, but panics if an error occurs.
func (tugb *TweetUserGroupBy) IntX(ctx context.Context) int {
	v, err := tugb.Int(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64s returns list of float64s from group-by.
// It is only allowed when executing a group-by query with one field.
func (tugb *TweetUserGroupBy) Float64s(ctx context.Context) ([]float64, error) {
	if len(tugb.fields) > 1 {
		return nil, errors.New("ent: TweetUserGroupBy.Float64s is not achievable when grouping more than 1 field")
	}
	var v []float64
	if err := tugb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// Float64sX is like Float64s, but panics if an error occurs.
func (tugb *TweetUserGroupBy) Float64sX(ctx context.Context) []float64 {
	v, err := tugb.Float64s(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64 returns a single float64 from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (tugb *TweetUserGroupBy) Float64(ctx context.Context) (_ float64, err error) {
	var v []float64
	if v, err = tugb.Float64s(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{tweetuser.Label}
	default:
		err = fmt.Errorf("ent: TweetUserGroupBy.Float64s returned %d results when one was expected", len(v))
	}
	return
}

// Float64X is like Float64, but panics if an error occurs.
func (tugb *TweetUserGroupBy) Float64X(ctx context.Context) float64 {
	v, err := tugb.Float64(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bools returns list of bools from group-by.
// It is only allowed when executing a group-by query with one field.
func (tugb *TweetUserGroupBy) Bools(ctx context.Context) ([]bool, error) {
	if len(tugb.fields) > 1 {
		return nil, errors.New("ent: TweetUserGroupBy.Bools is not achievable when grouping more than 1 field")
	}
	var v []bool
	if err := tugb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// BoolsX is like Bools, but panics if an error occurs.
func (tugb *TweetUserGroupBy) BoolsX(ctx context.Context) []bool {
	v, err := tugb.Bools(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bool returns a single bool from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (tugb *TweetUserGroupBy) Bool(ctx context.Context) (_ bool, err error) {
	var v []bool
	if v, err = tugb.Bools(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{tweetuser.Label}
	default:
		err = fmt.Errorf("ent: TweetUserGroupBy.Bools returned %d results when one was expected", len(v))
	}
	return
}

// BoolX is like Bool, but panics if an error occurs.
func (tugb *TweetUserGroupBy) BoolX(ctx context.Context) bool {
	v, err := tugb.Bool(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (tugb *TweetUserGroupBy) sqlScan(ctx context.Context, v interface{}) error {
	for _, f := range tugb.fields {
		if !tweetuser.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("invalid field %q for group-by", f)}
		}
	}
	selector := tugb.sqlQuery()
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := tugb.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

func (tugb *TweetUserGroupBy) sqlQuery() *sql.Selector {
	selector := tugb.sql.Select()
	aggregation := make([]string, 0, len(tugb.fns))
	for _, fn := range tugb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	// If no columns were selected in a custom aggregation function, the default
	// selection is the fields used for "group-by", and the aggregation functions.
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(tugb.fields)+len(tugb.fns))
		for _, f := range tugb.fields {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	return selector.GroupBy(selector.Columns(tugb.fields...)...)
}

// TweetUserSelect is the builder for selecting fields of TweetUser entities.
type TweetUserSelect struct {
	*TweetUserQuery
	// intermediate query (i.e. traversal path).
	sql *sql.Selector
}

// Scan applies the selector query and scans the result into the given value.
func (tus *TweetUserSelect) Scan(ctx context.Context, v interface{}) error {
	if err := tus.prepareQuery(ctx); err != nil {
		return err
	}
	tus.sql = tus.TweetUserQuery.sqlQuery(ctx)
	return tus.sqlScan(ctx, v)
}

// ScanX is like Scan, but panics if an error occurs.
func (tus *TweetUserSelect) ScanX(ctx context.Context, v interface{}) {
	if err := tus.Scan(ctx, v); err != nil {
		panic(err)
	}
}

// Strings returns list of strings from a selector. It is only allowed when selecting one field.
func (tus *TweetUserSelect) Strings(ctx context.Context) ([]string, error) {
	if len(tus.fields) > 1 {
		return nil, errors.New("ent: TweetUserSelect.Strings is not achievable when selecting more than 1 field")
	}
	var v []string
	if err := tus.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// StringsX is like Strings, but panics if an error occurs.
func (tus *TweetUserSelect) StringsX(ctx context.Context) []string {
	v, err := tus.Strings(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// String returns a single string from a selector. It is only allowed when selecting one field.
func (tus *TweetUserSelect) String(ctx context.Context) (_ string, err error) {
	var v []string
	if v, err = tus.Strings(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{tweetuser.Label}
	default:
		err = fmt.Errorf("ent: TweetUserSelect.Strings returned %d results when one was expected", len(v))
	}
	return
}

// StringX is like String, but panics if an error occurs.
func (tus *TweetUserSelect) StringX(ctx context.Context) string {
	v, err := tus.String(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Ints returns list of ints from a selector. It is only allowed when selecting one field.
func (tus *TweetUserSelect) Ints(ctx context.Context) ([]int, error) {
	if len(tus.fields) > 1 {
		return nil, errors.New("ent: TweetUserSelect.Ints is not achievable when selecting more than 1 field")
	}
	var v []int
	if err := tus.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// IntsX is like Ints, but panics if an error occurs.
func (tus *TweetUserSelect) IntsX(ctx context.Context) []int {
	v, err := tus.Ints(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Int returns a single int from a selector. It is only allowed when selecting one field.
func (tus *TweetUserSelect) Int(ctx context.Context) (_ int, err error) {
	var v []int
	if v, err = tus.Ints(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{tweetuser.Label}
	default:
		err = fmt.Errorf("ent: TweetUserSelect.Ints returned %d results when one was expected", len(v))
	}
	return
}

// IntX is like Int, but panics if an error occurs.
func (tus *TweetUserSelect) IntX(ctx context.Context) int {
	v, err := tus.Int(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64s returns list of float64s from a selector. It is only allowed when selecting one field.
func (tus *TweetUserSelect) Float64s(ctx context.Context) ([]float64, error) {
	if len(tus.fields) > 1 {
		return nil, errors.New("ent: TweetUserSelect.Float64s is not achievable when selecting more than 1 field")
	}
	var v []float64
	if err := tus.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// Float64sX is like Float64s, but panics if an error occurs.
func (tus *TweetUserSelect) Float64sX(ctx context.Context) []float64 {
	v, err := tus.Float64s(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64 returns a single float64 from a selector. It is only allowed when selecting one field.
func (tus *TweetUserSelect) Float64(ctx context.Context) (_ float64, err error) {
	var v []float64
	if v, err = tus.Float64s(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{tweetuser.Label}
	default:
		err = fmt.Errorf("ent: TweetUserSelect.Float64s returned %d results when one was expected", len(v))
	}
	return
}

// Float64X is like Float64, but panics if an error occurs.
func (tus *TweetUserSelect) Float64X(ctx context.Context) float64 {
	v, err := tus.Float64(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bools returns list of bools from a selector. It is only allowed when selecting one field.
func (tus *TweetUserSelect) Bools(ctx context.Context) ([]bool, error) {
	if len(tus.fields) > 1 {
		return nil, errors.New("ent: TweetUserSelect.Bools is not achievable when selecting more than 1 field")
	}
	var v []bool
	if err := tus.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// BoolsX is like Bools, but panics if an error occurs.
func (tus *TweetUserSelect) BoolsX(ctx context.Context) []bool {
	v, err := tus.Bools(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bool returns a single bool from a selector. It is only allowed when selecting one field.
func (tus *TweetUserSelect) Bool(ctx context.Context) (_ bool, err error) {
	var v []bool
	if v, err = tus.Bools(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{tweetuser.Label}
	default:
		err = fmt.Errorf("ent: TweetUserSelect.Bools returned %d results when one was expected", len(v))
	}
	return
}

// BoolX is like Bool, but panics if an error occurs.
func (tus *TweetUserSelect) BoolX(ctx context.Context) bool {
	v, err := tus.Bool(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (tus *TweetUserSelect) sqlScan(ctx context.Context, v interface{}) error {
	rows := &sql.Rows{}
	query, args := tus.sql.Query()
	if err := tus.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
