// Code generated by entc, DO NOT EDIT.

package sender

const (
	// Label holds the string label denoting the sender type in the database.
	Label = "sender"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldUsername holds the string denoting the username field in the database.
	FieldUsername = "username"
	// Table holds the table name of the sender in the database.
	Table = "senders"
)

// Columns holds all SQL columns for sender fields.
var Columns = []string{
	FieldID,
	FieldUsername,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}
