package bot

import "gopkg.in/telebot.v3"

var listenTo = []string{
	telebot.OnEdited,
	telebot.OnPhoto,
	telebot.OnAudio,
	telebot.OnDocument,
	telebot.OnSticker,
	telebot.OnText,
	telebot.OnVideo,
	telebot.OnVoice,
	telebot.OnVideoNote,
	telebot.OnAnimation,
	telebot.OnContact,
	telebot.OnLocation,
	telebot.OnVenue,
	telebot.OnDice,
	telebot.OnInvoice,
	telebot.OnPayment,
	telebot.OnGame,
	telebot.OnPoll,
	telebot.OnPollAnswer,
	telebot.OnPinned,
	telebot.OnChannelPost,
	telebot.OnEditedChannelPost,
	telebot.OnAddedToGroup,
	telebot.OnUserJoined,
	telebot.OnUserLeft,
	telebot.OnNewGroupTitle,
	telebot.OnNewGroupPhoto,
	telebot.OnGroupPhotoDeleted,
	telebot.OnGroupCreated,
	telebot.OnSuperGroupCreated,
	telebot.OnChannelCreated,
	telebot.OnMigration,
	telebot.OnMedia,
	telebot.OnCallback,
	telebot.OnQuery,
	telebot.OnInlineResult,
	telebot.OnShipping,
	telebot.OnCheckout,
	telebot.OnMyChatMember,
	telebot.OnChatMember,
	telebot.OnChatJoinRequest,
	telebot.OnVoiceChatStarted,
	telebot.OnVoiceChatEnded,
	telebot.OnVoiceChatParticipants,
	telebot.OnVoiceChatScheduled,
	telebot.OnProximityAlert,
	telebot.OnAutoDeleteTimer,
}
